/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.escolhas;

/**
 *
 * @author Welington
 */
public class EscolhaFigEsp extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaFigEsp
     */
    public EscolhaFigEsp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickPiramide = new javax.swing.JLabel();
        clickTetraedro = new javax.swing.JLabel();
        clickParalelepipedo = new javax.swing.JLabel();
        clickCone = new javax.swing.JLabel();
        clickCilindro = new javax.swing.JLabel();
        clickEsfera = new javax.swing.JLabel();
        clickPrisma = new javax.swing.JLabel();
        clickCubo = new javax.swing.JLabel();
        titleCubo = new javax.swing.JLabel();
        titlePrisma = new javax.swing.JLabel();
        titleEsfera = new javax.swing.JLabel();
        titleCilindro = new javax.swing.JLabel();
        titlePiramide = new javax.swing.JLabel();
        titleTetraedro = new javax.swing.JLabel();
        titleParalelepipedo = new javax.swing.JLabel();
        titleCone = new javax.swing.JLabel();
        seta = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(693, 368));
        setUndecorated(true);
        getContentPane().setLayout(null);

        clickPiramide.setToolTipText("Clique para acessar");
        clickPiramide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickPiramide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickPiramideMouseDragged(evt);
            }
        });
        clickPiramide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPiramideMouseClicked(evt);
            }
        });
        getContentPane().add(clickPiramide);
        clickPiramide.setBounds(520, 240, 100, 110);

        clickTetraedro.setToolTipText("Clique para acessar");
        clickTetraedro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickTetraedro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickTetraedroMouseDragged(evt);
            }
        });
        clickTetraedro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTetraedroMouseClicked(evt);
            }
        });
        getContentPane().add(clickTetraedro);
        clickTetraedro.setBounds(370, 240, 100, 110);

        clickParalelepipedo.setToolTipText("Clique para acessar");
        clickParalelepipedo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickParalelepipedo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickParalelepipedoMouseDragged(evt);
            }
        });
        clickParalelepipedo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickParalelepipedoMouseClicked(evt);
            }
        });
        getContentPane().add(clickParalelepipedo);
        clickParalelepipedo.setBounds(220, 240, 100, 110);

        clickCone.setToolTipText("Clique para acessar");
        clickCone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickCone.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickConeMouseDragged(evt);
            }
        });
        clickCone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickConeMouseClicked(evt);
            }
        });
        getContentPane().add(clickCone);
        clickCone.setBounds(70, 240, 100, 110);

        clickCilindro.setToolTipText("Clique para acessar");
        clickCilindro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickCilindro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickCilindroMouseDragged(evt);
            }
        });
        clickCilindro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCilindroMouseClicked(evt);
            }
        });
        getContentPane().add(clickCilindro);
        clickCilindro.setBounds(520, 90, 100, 110);

        clickEsfera.setToolTipText("Clique para acessar");
        clickEsfera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickEsfera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickEsferaMouseDragged(evt);
            }
        });
        clickEsfera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickEsferaMouseClicked(evt);
            }
        });
        getContentPane().add(clickEsfera);
        clickEsfera.setBounds(370, 90, 100, 110);

        clickPrisma.setToolTipText("Clique para acessar");
        clickPrisma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickPrisma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickPrismaMouseDragged(evt);
            }
        });
        clickPrisma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPrismaMouseClicked(evt);
            }
        });
        getContentPane().add(clickPrisma);
        clickPrisma.setBounds(220, 90, 100, 110);

        clickCubo.setToolTipText("Clique para acessar");
        clickCubo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickCubo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clickCuboMouseDragged(evt);
            }
        });
        clickCubo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickCuboMouseClicked(evt);
            }
        });
        getContentPane().add(clickCubo);
        clickCubo.setBounds(70, 90, 100, 110);

        titleCubo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleCubo.setForeground(new java.awt.Color(255, 224, 101));
        titleCubo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCubo.setText("Cubo");
        getContentPane().add(titleCubo);
        titleCubo.setBounds(100, 70, 32, 17);

        titlePrisma.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titlePrisma.setForeground(new java.awt.Color(255, 224, 101));
        titlePrisma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePrisma.setText("Prisma");
        getContentPane().add(titlePrisma);
        titlePrisma.setBounds(240, 70, 60, 17);

        titleEsfera.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleEsfera.setForeground(new java.awt.Color(255, 224, 101));
        titleEsfera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleEsfera.setText("Esfera");
        getContentPane().add(titleEsfera);
        titleEsfera.setBounds(390, 70, 60, 17);

        titleCilindro.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleCilindro.setForeground(new java.awt.Color(255, 224, 101));
        titleCilindro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCilindro.setText("Cilindro");
        getContentPane().add(titleCilindro);
        titleCilindro.setBounds(540, 70, 60, 17);

        titlePiramide.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titlePiramide.setForeground(new java.awt.Color(255, 224, 101));
        titlePiramide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePiramide.setText("Pirâmide");
        getContentPane().add(titlePiramide);
        titlePiramide.setBounds(520, 220, 100, 17);

        titleTetraedro.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleTetraedro.setForeground(new java.awt.Color(255, 224, 101));
        titleTetraedro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTetraedro.setText("Tetraedro");
        getContentPane().add(titleTetraedro);
        titleTetraedro.setBounds(370, 220, 100, 17);

        titleParalelepipedo.setFont(new java.awt.Font("Segoe UI Black", 0, 9)); // NOI18N
        titleParalelepipedo.setForeground(new java.awt.Color(255, 224, 101));
        titleParalelepipedo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleParalelepipedo.setText("Paralelepípedo");
        getContentPane().add(titleParalelepipedo);
        titleParalelepipedo.setBounds(220, 220, 100, 17);

        titleCone.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleCone.setForeground(new java.awt.Color(255, 224, 101));
        titleCone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCone.setText("Cone");
        getContentPane().add(titleCone);
        titleCone.setBounds(90, 220, 60, 17);

        seta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FigEspaciais/seta-02.png"))); // NOI18N
        seta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setaMouseClicked(evt);
            }
        });
        getContentPane().add(seta);
        seta.setBounds(10, 0, 70, 70);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FigEspaciais/figGeoEsp.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 710, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickCuboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickCuboMouseClicked
        TipoCalculoCubo tcc = new TipoCalculoCubo();
        tcc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickCuboMouseClicked

    private void clickCuboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickCuboMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clickCuboMouseDragged

    private void clickPrismaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPrismaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickPrismaMouseDragged

    private void clickPrismaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPrismaMouseClicked
        TipoCalculoPrisma tcp = new TipoCalculoPrisma();
        tcp.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_clickPrismaMouseClicked

    private void clickEsferaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickEsferaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickEsferaMouseDragged

    private void clickEsferaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickEsferaMouseClicked
        TipoCalculoEsfera tce = new TipoCalculoEsfera();
        tce.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_clickEsferaMouseClicked

    private void clickCilindroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickCilindroMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickCilindroMouseDragged

    private void clickCilindroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickCilindroMouseClicked
        TipoCalculoCilindro tcc = new TipoCalculoCilindro();
        tcc.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_clickCilindroMouseClicked

    private void clickConeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickConeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickConeMouseDragged

    private void clickConeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickConeMouseClicked
        TipoCalculoCone tcc = new TipoCalculoCone();
        tcc.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_clickConeMouseClicked

    private void clickParalelepipedoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickParalelepipedoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickParalelepipedoMouseDragged

    private void clickParalelepipedoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickParalelepipedoMouseClicked
         TipoCalculoParalelepípedo tcp = new TipoCalculoParalelepípedo();
         tcp.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_clickParalelepipedoMouseClicked

    private void clickTetraedroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTetraedroMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickTetraedroMouseDragged

    private void clickTetraedroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTetraedroMouseClicked
         TipoCalculoTetraedro tct = new TipoCalculoTetraedro();
         tct.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_clickTetraedroMouseClicked

    private void clickPiramideMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPiramideMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clickPiramideMouseDragged

    private void clickPiramideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPiramideMouseClicked
         TipoCalculoPiramide tcp = new TipoCalculoPiramide();
         tcp.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_clickPiramideMouseClicked

    private void setaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setaMouseClicked
        EscolhaTipFig etf = new EscolhaTipFig();
        etf.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_setaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaFigEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaFigEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaFigEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaFigEsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaFigEsp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickCilindro;
    private javax.swing.JLabel clickCone;
    private javax.swing.JLabel clickCubo;
    private javax.swing.JLabel clickEsfera;
    private javax.swing.JLabel clickParalelepipedo;
    private javax.swing.JLabel clickPiramide;
    private javax.swing.JLabel clickPrisma;
    private javax.swing.JLabel clickTetraedro;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel seta;
    private javax.swing.JLabel titleCilindro;
    private javax.swing.JLabel titleCone;
    private javax.swing.JLabel titleCubo;
    private javax.swing.JLabel titleEsfera;
    private javax.swing.JLabel titleParalelepipedo;
    private javax.swing.JLabel titlePiramide;
    private javax.swing.JLabel titlePrisma;
    private javax.swing.JLabel titleTetraedro;
    // End of variables declaration//GEN-END:variables
}
