/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal.calcexpress.Menu;

/**
 *
 * @author Alunos
 */
public class Equipe extends javax.swing.JFrame {

    /**
     * Creates new form Equipe
     */
    public Equipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoEq = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        seta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descriequip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(699, 362));
        setUndecorated(true);
        getContentPane().setLayout(null);

        logoEq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobrecalc/logoEq.png"))); // NOI18N
        getContentPane().add(logoEq);
        logoEq.setBounds(80, 50, 220, 220);

        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name1.setText("Camila");
        getContentPane().add(name1);
        name1.setBounds(50, 340, 50, 16);

        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name2.setText("Anderson");
        getContentPane().add(name2);
        name2.setBounds(110, 340, 90, 16);

        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name3.setText("P.Farias");
        getContentPane().add(name3);
        name3.setBounds(190, 340, 70, 16);

        name4.setBackground(new java.awt.Color(255, 255, 255));
        name4.setForeground(new java.awt.Color(255, 255, 255));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name4.setText("Enzo");
        getContentPane().add(name4);
        name4.setBounds(270, 340, 50, 16);

        seta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobrecalc/seta-04.png"))); // NOI18N
        seta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setaMouseClicked(evt);
            }
        });
        getContentPane().add(seta);
        seta.setBounds(10, 10, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobrecalc/fotos.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 270, 290, 80);

        descriequip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobrecalc/descri.equip.png"))); // NOI18N
        getContentPane().add(descriequip);
        descriequip.setBounds(360, 30, 280, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobrecalc/sobre.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setaMouseClicked
        // TODO add your handling code here:
         Menu mn = new Menu();
         mn.setVisible(true);
         mn.pack();
         mn.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_setaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriequip;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoEq;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel seta;
    // End of variables declaration//GEN-END:variables
}
