/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.telasdadosplanas;

import br.edu.escolhas.EscolhaFigPlan;
import br.edu.escolhas.UsarNovamente;
import br.edu.figurasgeometricasplanas.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MANUELA
 */
public class DadosAreaParalelogramo extends javax.swing.JFrame {

    /**
     * Creates new form DadosAreaParalelogramo
     */
    public DadosAreaParalelogramo() {
        initComponents();
        this.setResizable(false);
        ImageIcon icon = new ImageIcon((new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/icon.png")).getImage()));  
        setIconImage(icon.getImage());
        caixa_area.setVisible(false);
        texto_area.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_reset = new javax.swing.JButton();
        botao_calc = new javax.swing.JButton();
        texto_b = new javax.swing.JLabel();
        texto_al = new javax.swing.JLabel();
        texto_area = new javax.swing.JLabel();
        caixa_area = new javax.swing.JTextField();
        BaseText = new javax.swing.JTextField();
        AlturaText = new javax.swing.JTextField();
        tela = new javax.swing.JLabel();
        BarMenu1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_reset.setBackground(new java.awt.Color(153, 0, 0));
        botao_reset.setForeground(new java.awt.Color(255, 255, 255));
        botao_reset.setText("Resetar");
        botao_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_resetActionPerformed(evt);
            }
        });
        getContentPane().add(botao_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        botao_calc.setBackground(new java.awt.Color(153, 0, 0));
        botao_calc.setForeground(new java.awt.Color(255, 255, 255));
        botao_calc.setText("Calcular");
        botao_calc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_calcActionPerformed(evt);
            }
        });
        getContentPane().add(botao_calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        texto_b.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_b.setForeground(new java.awt.Color(153, 0, 0));
        texto_b.setText("Base");
        getContentPane().add(texto_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        texto_al.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_al.setForeground(new java.awt.Color(153, 0, 0));
        texto_al.setText("Altura");
        getContentPane().add(texto_al, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        texto_area.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_area.setForeground(new java.awt.Color(153, 0, 0));
        texto_area.setText("Área");
        getContentPane().add(texto_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(caixa_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, -1));

        BaseText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaseTextMouseClicked(evt);
            }
        });
        BaseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseTextActionPerformed(evt);
            }
        });
        getContentPane().add(BaseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, -1));

        AlturaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlturaTextMouseClicked(evt);
            }
        });
        AlturaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaTextActionPerformed(evt);
            }
        });
        getContentPane().add(AlturaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 240, -1));

        tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/ParalelogramoDados.png"))); // NOI18N
        tela.setPreferredSize(new java.awt.Dimension(699, 374));
        getContentPane().add(tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        jMenu6.setForeground(new java.awt.Color(51, 0, 51));
        jMenu6.setText("Menu");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/retornar.png"))); // NOI18N
        jMenu7.setText("Retornar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu7);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/sair.png"))); // NOI18N
        jMenu4.setText("Sair");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu4);

        BarMenu1.add(jMenu6);

        setJMenuBar(BarMenu1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BaseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseTextActionPerformed

    private void AlturaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaTextActionPerformed

    private void botao_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_resetActionPerformed
        caixa_area.setVisible(false);
        texto_area.setVisible(false);
        BaseText.setText("");
        botao_calc.setText("Calcular");
        AlturaText.setText("");        
    }//GEN-LAST:event_botao_resetActionPerformed

    private void botao_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_calcActionPerformed
        if(botao_calc.getText().equals("Próximo")){
                UsarNovamente un = new UsarNovamente();
                un.setVisible(true); 
                this.dispose();
        }
        
        try{
        if (BaseText.getText().trim().equals("")){
                   BaseText.setText("Campo Vazio");
        }
        else if (Double.parseDouble(BaseText.getText()) <= 0){
                   BaseText.setText("Valor Não Aceito");
        }
            
        if (AlturaText.getText().trim().equals("")){
                AlturaText.setText("Campo Vazio");
        }
        else if (Double.parseDouble(AlturaText.getText()) <= 0){
                AlturaText.setText("Valor Não Aceito");
        }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Não digite letras.");
        }
        
        Paralelogramo paral = new Paralelogramo();
        
        if ((((Double.parseDouble(BaseText.getText() ))) > 0) && ((Double.parseDouble(AlturaText.getText() )) > 0)) {
           paral.setBase(Double.parseDouble(BaseText.getText()));
           paral.setAltura(Double.parseDouble(AlturaText.getText()));
           paral.CalcArea1();
        
           caixa_area.setVisible(true);
           texto_area.setVisible(true);
           caixa_area.setText(String.format("%.2f", paral.getArea()));
        
           botao_calc.setText("Próximo");   
        }
    }//GEN-LAST:event_botao_calcActionPerformed

    private void BaseTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaseTextMouseClicked
         if ((BaseText.getText().equals("Campo Vazio")) || (BaseText.getText().equals("Valor Não Aceito"))){
                  BaseText.setText("");
        }
    }//GEN-LAST:event_BaseTextMouseClicked

    private void AlturaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlturaTextMouseClicked
         if ((AlturaText.getText().equals("Campo Vazio")) || (AlturaText.getText().equals("Valor Não Aceito"))){
                  AlturaText.setText("");
        }
    }//GEN-LAST:event_AlturaTextMouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
          EscolhaFigPlan efp = new EscolhaFigPlan();
        efp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked

    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosAreaParalelogramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosAreaParalelogramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosAreaParalelogramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosAreaParalelogramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosAreaParalelogramo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaText;
    private javax.swing.JMenuBar BarMenu1;
    private javax.swing.JTextField BaseText;
    private javax.swing.JButton botao_calc;
    private javax.swing.JButton botao_reset;
    private javax.swing.JTextField caixa_area;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JLabel tela;
    private javax.swing.JLabel texto_al;
    private javax.swing.JLabel texto_area;
    private javax.swing.JLabel texto_b;
    // End of variables declaration//GEN-END:variables
}
