/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.telasdadosplanas;

import br.edu.escolhas.EscolhaFigPlan;
import br.edu.escolhas.UsarNovamente;
import br.edu.figurasgeometricasplanas.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MANUELA
 */
public class DadosAreaQuadrado extends javax.swing.JFrame {

    /**
     * Creates new form DadosAreaCirculo
     */
    public DadosAreaQuadrado() {
        initComponents();
        this.setResizable(false);
        ImageIcon icon = new ImageIcon((new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/icon.png")).getImage()));  
        setIconImage(icon.getImage());
        caixa_area.setVisible(false);
        texto_area.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto_lado = new javax.swing.JLabel();
        caixa_lado = new javax.swing.JFormattedTextField();
        texto_area = new javax.swing.JLabel();
        caixa_area = new javax.swing.JFormattedTextField();
        botao_reset = new javax.swing.JButton();
        botao_calc = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        BarMenu1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(699, 374));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto_lado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_lado.setForeground(new java.awt.Color(153, 0, 0));
        texto_lado.setText("Lado");
        getContentPane().add(texto_lado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        caixa_lado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixa_ladoMouseClicked(evt);
            }
        });
        getContentPane().add(caixa_lado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, -1));

        texto_area.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_area.setForeground(new java.awt.Color(153, 0, 0));
        texto_area.setText("Área");
        getContentPane().add(texto_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        caixa_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_areaActionPerformed(evt);
            }
        });
        getContentPane().add(caixa_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 250, -1));

        botao_reset.setBackground(new java.awt.Color(153, 0, 0));
        botao_reset.setForeground(new java.awt.Color(255, 255, 255));
        botao_reset.setText("Resetar");
        botao_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_resetActionPerformed(evt);
            }
        });
        getContentPane().add(botao_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        botao_calc.setBackground(new java.awt.Color(153, 0, 0));
        botao_calc.setForeground(new java.awt.Color(255, 255, 255));
        botao_calc.setText("Calcular");
        botao_calc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_calcActionPerformed(evt);
            }
        });
        getContentPane().add(botao_calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/QuadradoDados.png"))); // NOI18N
        getContentPane().add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        jMenu6.setForeground(new java.awt.Color(51, 0, 51));
        jMenu6.setText("Menu");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/retornar.png"))); // NOI18N
        jMenu7.setText("Retornar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu7);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/sair.png"))); // NOI18N
        jMenu4.setText("Sair");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu4);

        BarMenu1.add(jMenu6);

        setJMenuBar(BarMenu1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_calcActionPerformed
       if(botao_calc.getText().equals("Próximo")){
                UsarNovamente un = new UsarNovamente();
                un.setVisible(true); 
                this.dispose();
        }
        
        try {
          if (caixa_lado.getText().trim().equals("")){
                   caixa_lado.setText("Campo Vazio");
          }
          else if (Double.parseDouble(caixa_lado.getText()) <= 0){
                   caixa_lado.setText("Valor Não Aceito");
          }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Não digite letras.");
        }
       if ((((Double.parseDouble(caixa_lado.getText() ))) > 0)){
        
        Quadrado quad = new Quadrado();
        quad.setLado(Double.parseDouble(caixa_lado.getText()));
        quad.CalcArea1();
        
        caixa_area.setVisible(true);
        texto_area.setVisible(true);
        caixa_area.setText(String.format("%.2f", quad.getArea()));
        
        
         botao_calc.setText("Próximo");
       }
    }//GEN-LAST:event_botao_calcActionPerformed

    private void botao_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_resetActionPerformed
       
        caixa_area.setVisible(false);
        texto_area.setVisible(false);
        caixa_lado.setText("");
        botao_calc.setText("Calcular");
                
    }//GEN-LAST:event_botao_resetActionPerformed

    private void caixa_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_areaActionPerformed

    private void caixa_ladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixa_ladoMouseClicked
        if ((caixa_lado.getText().equals("Campo Vazio")) || (caixa_lado.getText().equals("Valor Não Aceito"))){
                  caixa_lado.setText("");
        }
    }//GEN-LAST:event_caixa_ladoMouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
         EscolhaFigPlan efp = new EscolhaFigPlan();
        efp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked

    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosAreaQuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosAreaQuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosAreaQuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosAreaQuadrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosAreaQuadrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarMenu1;
    private javax.swing.JButton botao_calc;
    private javax.swing.JButton botao_reset;
    private javax.swing.JFormattedTextField caixa_area;
    private javax.swing.JFormattedTextField caixa_lado;
    private javax.swing.JLabel imagem;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JLabel texto_area;
    private javax.swing.JLabel texto_lado;
    // End of variables declaration//GEN-END:variables
}
