/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.telasdadosplanas;

import br.edu.escolhas.EscolhaFigPlan;
import br.edu.escolhas.UsarNovamente;
import br.edu.figurasgeometricasplanas.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MANUELA
 */
public class DadosAreaTrapezio extends javax.swing.JFrame {

    

    

    /**
     * Creates new form DadosAreaLosango
     */
    public DadosAreaTrapezio() {
        initComponents();
        this.setResizable(false);
        ImageIcon icon = new ImageIcon((new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/icon.png")).getImage()));
        setIconImage(icon.getImage());
        Caixa_Area.setVisible(false);
        Texto_Area.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_Bm = new javax.swing.JLabel();
        Texto_Area = new javax.swing.JLabel();
        Texto_bm = new javax.swing.JLabel();
        texto_al = new javax.swing.JLabel();
        AlturaText = new javax.swing.JTextField();
        Caixa_Area = new javax.swing.JTextField();
        BaseMText = new javax.swing.JTextField();
        BasemText = new javax.swing.JTextField();
        botao_reset = new javax.swing.JButton();
        botao_calc = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        BarMenu1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Bm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Texto_Bm.setForeground(new java.awt.Color(255, 0, 0));
        Texto_Bm.setText("Base Maior");
        getContentPane().add(Texto_Bm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Texto_Area.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Texto_Area.setForeground(new java.awt.Color(255, 0, 0));
        Texto_Area.setText("Área");
        getContentPane().add(Texto_Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Texto_bm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Texto_bm.setForeground(new java.awt.Color(255, 0, 0));
        Texto_bm.setText("Base Menor");
        getContentPane().add(Texto_bm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        texto_al.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texto_al.setForeground(new java.awt.Color(255, 0, 0));
        texto_al.setText("Altura");
        getContentPane().add(texto_al, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        AlturaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaTextActionPerformed(evt);
            }
        });
        getContentPane().add(AlturaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 350, -1));

        Caixa_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa_AreaActionPerformed(evt);
            }
        });
        getContentPane().add(Caixa_Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 350, -1));

        BaseMText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaseMTextMouseClicked(evt);
            }
        });
        BaseMText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseMTextActionPerformed(evt);
            }
        });
        getContentPane().add(BaseMText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 350, -1));

        BasemText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BasemTextMouseClicked(evt);
            }
        });
        BasemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasemTextActionPerformed(evt);
            }
        });
        getContentPane().add(BasemText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 350, -1));

        botao_reset.setBackground(new java.awt.Color(153, 0, 0));
        botao_reset.setForeground(new java.awt.Color(255, 255, 255));
        botao_reset.setText("Resetar");
        botao_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_resetActionPerformed(evt);
            }
        });
        getContentPane().add(botao_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        botao_calc.setBackground(new java.awt.Color(153, 0, 0));
        botao_calc.setForeground(new java.awt.Color(255, 255, 255));
        botao_calc.setText("Calcular");
        botao_calc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_calcMouseClicked(evt);
            }
        });
        botao_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_calcActionPerformed(evt);
            }
        });
        getContentPane().add(botao_calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/telasimagens/TrapezioDados.png"))); // NOI18N
        imagem.setMaximumSize(new java.awt.Dimension(699, 374));
        imagem.setMinimumSize(new java.awt.Dimension(699, 374));
        imagem.setPreferredSize(new java.awt.Dimension(699, 374));
        getContentPane().add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        jMenu6.setForeground(new java.awt.Color(51, 0, 51));
        jMenu6.setText("Menu");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/retornar.png"))); // NOI18N
        jMenu7.setText("Retornar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu7);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/sair.png"))); // NOI18N
        jMenu4.setText("Sair");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu4);

        BarMenu1.add(jMenu6);

        setJMenuBar(BarMenu1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Caixa_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa_AreaActionPerformed

    private void BaseMTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseMTextActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_BaseMTextActionPerformed

    private void botao_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_resetActionPerformed
        
        Caixa_Area.setVisible(false);
        Texto_Area.setVisible(false);
        botao_calc.setText("Calcular");
        BaseMText.setText("");
        BasemText.setText("");
        AlturaText.setText("");
       
    }//GEN-LAST:event_botao_resetActionPerformed

    private void botao_calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_calcMouseClicked
        
    }//GEN-LAST:event_botao_calcMouseClicked

    private void botao_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_calcActionPerformed
       if(botao_calc.getText().equals("Próximo")){
                UsarNovamente un = new UsarNovamente();
                un.setVisible(true); 
                this.dispose();
        }
        
       try {
        if (BaseMText.getText().trim().equals("")){
                   BaseMText.setText("Campo Vazio");
       }
       else if (Double.parseDouble(BaseMText.getText()) <= 0){
                   BaseMText.setText("Valor Não Aceito");
       }
        
       if (BasemText.getText().trim().equals("")){
                   BasemText.setText("Campo Vazio");
       }
       else if (Double.parseDouble(BasemText.getText()) <= 0){
                   BasemText.setText("Valor Não Aceito");
       }
       else if (Double.parseDouble(BasemText.getText()) >= (Double.parseDouble(BaseMText.getText()))){
                   BasemText.setText("Base Menor precisa ser menor que a Base Maior.");
       }
            
       if (AlturaText.getText().trim().equals("")){
                AlturaText.setText("Campo Vazio");
       }
       else if (Double.parseDouble(AlturaText.getText()) <= 0){
                AlturaText.setText("Valor Não Aceito");
       }
       } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Não digite letras.");
       }
       Trapezio trap = new Trapezio();
        
       if ((((Double.parseDouble(BaseMText.getText() ))) > 0) && ((Double.parseDouble(BasemText.getText())) > 0) && ((Double.parseDouble(AlturaText.getText() )) > 0)) {
        trap.setBaseMaior(Double.parseDouble(BaseMText.getText()));
        trap.setBaseMenor(Double.parseDouble(BasemText.getText()));
        trap.setAltura(Double.parseDouble(AlturaText.getText()));
        trap.CalcArea1();
        
        Caixa_Area.setVisible(true);
        Texto_Area.setVisible(true);
        Caixa_Area.setText(String.format("%.2f", trap.getArea()));
        
        
        botao_calc.setText("Próximo");   
      }
    }//GEN-LAST:event_botao_calcActionPerformed

    private void BasemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasemTextActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_BasemTextActionPerformed

    private void AlturaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaTextActionPerformed

    private void BaseMTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaseMTextMouseClicked
        if ((BaseMText.getText().equals("Campo Vazio")) || (BaseMText.getText().equals("Valor Não Aceito"))){
                  BaseMText.setText("");
        }
    }//GEN-LAST:event_BaseMTextMouseClicked

    private void BasemTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasemTextMouseClicked
        if ((BasemText.getText().equals("Campo Vazio")) || (BasemText.getText().equals("Valor Não Aceito")) || (BasemText.getText().equals("Base Menor precisa ser menor que a Base Maior."))){
                  BasemText.setText("");
        }
    }//GEN-LAST:event_BasemTextMouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
          EscolhaFigPlan efp = new EscolhaFigPlan();
        efp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked

    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosAreaTrapezio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosAreaTrapezio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosAreaTrapezio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosAreaTrapezio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosAreaTrapezio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaText;
    private javax.swing.JMenuBar BarMenu1;
    private javax.swing.JTextField BaseMText;
    private javax.swing.JTextField BasemText;
    private javax.swing.JTextField Caixa_Area;
    private javax.swing.JLabel Texto_Area;
    private javax.swing.JLabel Texto_Bm;
    private javax.swing.JLabel Texto_bm;
    private javax.swing.JButton botao_calc;
    private javax.swing.JButton botao_reset;
    private javax.swing.JLabel imagem;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JLabel texto_al;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
