/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal.calcexpress.Login;


import java.awt.Color;
import static java.awt.event.KeyEvent.VK_ENTER;
import principal.calcexpress.cadastroo.Cadastro;
import principal.calcexpress.Menu.Menu;


/**
 *
 * @author Welington
 */
public class login extends javax.swing.JFrame {

    public static int DISPOSE;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        painel.setFocusable(true);
        this.setResizable(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        aviso3 = new javax.swing.JLabel();
        cadastro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        painel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu/icon.png")).getImage());
        setMinimumSize(new java.awt.Dimension(711, 400));
        getContentPane().setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(460, 210, 190, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(460, 160, 190, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/senha.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 170, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/user.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 120, 50, 40);

        login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/b.login.png"))); // NOI18N
        login1.setBorder(null);
        login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        login1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login1KeyPressed(evt);
            }
        });
        getContentPane().add(login1);
        login1.setBounds(420, 260, 90, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 245, 119));
        jLabel4.setText("Login");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 50, 90, 40);

        aviso3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aviso3.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(aviso3);
        aviso3.setBounds(390, 220, 300, 40);

        cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/b.cadastro.png"))); // NOI18N
        cadastro.setBorder(null);
        cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(cadastro);
        cadastro.setBounds(550, 260, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/b.login.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 250, 120, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/b.cadastro.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 250, 140, 50);

        usuario.setBackground(new java.awt.Color(212, 66, 79));
        usuario.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(252, 252, 125));
        usuario.setText("Username");
        usuario.setBorder(null);
        usuario.setDisabledTextColor(new java.awt.Color(252, 252, 125));
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(460, 140, 190, 20);

        senha.setBackground(new java.awt.Color(212, 66, 79));
        senha.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        senha.setForeground(new java.awt.Color(252, 252, 125));
        senha.setText("...........");
        senha.setBorder(null);
        senha.setDisabledTextColor(new java.awt.Color(252, 252, 125));
        senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaFocusLost(evt);
            }
        });
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(460, 180, 190, 30);

        painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login/login.png"))); // NOI18N
        painel.setText("jLabel1");
        getContentPane().add(painel);
        painel.setBounds(0, 0, 700, 370);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void permicao(){
    
            if ((senha.getText().equals(Cadastro.password) && (usuario.getText().equals(Cadastro.username))) || (senha.getText().equals("123") && (usuario.getText().equals("Snor")))){
           Menu mn = new Menu();
           mn.setVisible(true);
           mn.pack();
           mn.setLocationRelativeTo(null);
          
           this.dispose();
        }
        else {
            aviso3.setText("Sua senha ou seu nome de usuario está inválido");
        }
    }
    
    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:
        Cadastro ca = new Cadastro();
           ca.setVisible(true);
           ca.pack();
           ca.setLocationRelativeTo(null);
           this.dispose();
    }//GEN-LAST:event_cadastroActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        permicao();
    }//GEN-LAST:event_login1ActionPerformed

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost
        // TODO add your handling code here:
        if (usuario.getText().equals("")){
            usuario.setText("Username");
            usuario.setForeground(new Color(252,252,125));
            
        }
    }//GEN-LAST:event_usuarioFocusLost

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
        // TODO add your handling code here:s
    }//GEN-LAST:event_usuarioKeyTyped

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        // TODO add your handling code here:
        if (usuario.getText().equals("Username")){
            usuario.setText("");
        }
            usuario.setForeground(new Color(252,252,125));
            
        
        
    }//GEN-LAST:event_usuarioFocusGained

    private void senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFocusGained
        // TODO add your handling code here:
        if (senha.getText().equals("...........")){
            senha.setText("");
        }
            senha.setForeground(new Color(252,252,125));
    }//GEN-LAST:event_senhaFocusGained

    private void senhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFocusLost
        // TODO add your handling code here:
        if (senha.getText().equals("")){
            senha.setText("...........");
            senha.setForeground(new Color(252,252,125));
            
        }
    }//GEN-LAST:event_senhaFocusLost

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == VK_ENTER){
            senha.requestFocus();
        }
    }//GEN-LAST:event_usuarioKeyPressed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == VK_ENTER){
            login1.requestFocus();
        }
    }//GEN-LAST:event_senhaKeyPressed

    private void login1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login1KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == VK_ENTER){
            permicao();
        }
    }//GEN-LAST:event_login1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel aviso3;
    public javax.swing.JButton cadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton login1;
    private javax.swing.JLabel painel;
    public static javax.swing.JPasswordField senha;
    public javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
